export const stacks = {
    'Python':'blue',
    'java':'blue',
    'Spring':'green',
    'AWS':'yellow',
    'oracle':'red',
    'iOS':'black',
    'HTML' :'red',
    'MySQL':'blue',
    'SQL':'blue',
    'JavaScipt':'yellow',
    'firebase':'yellow',
    'Andriod':'green',
    'mariaDB':'green',
    'mongoDB':'green',
    'C/C++':'blue',
    'React':'blue',
    'vue':'green',
    'angular':'red',
    'node':'green',
    'express':'black',
    'django':'green',
    'flutter':'blue',
};

export const editMode ={
    delete : 'delete',
    modify : 'modify',
    unEdit : false,
};